from PySide2 import QtCore, QtGui, QtWidgets

class Ui_COS(object):
    def setupUi(self, COS):
        COS.setObjectName("COS")
        COS.resize(817, 610)
        self.centralwidget = QtWidgets.QWidget(COS)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.le_num = QtWidgets.QLineEdit(self.centralwidget)
        self.le_num.setMinimumSize(QtCore.QSize(0, 0))
        self.le_num.setMaximumSize(QtCore.QSize(16777215, 25))
        self.le_num.setObjectName("le_num")
        self.verticalLayout_3.addWidget(self.le_num)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.pbtn_DF = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_DF.setObjectName("pbtn_DF")
        self.verticalLayout_3.addWidget(self.pbtn_DF)
        self.pbtn_XD = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_XD.setObjectName("pbtn_XD")
        self.verticalLayout_3.addWidget(self.pbtn_XD)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.le_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_1.setMinimumSize(QtCore.QSize(0, 25))
        self.le_1.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_1.setAlignment(QtCore.Qt.AlignCenter)
        self.le_1.setObjectName("le_1")
        self.verticalLayout_2.addWidget(self.le_1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.le_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_2.setMinimumSize(QtCore.QSize(0, 25))
        self.le_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_2.setAlignment(QtCore.Qt.AlignCenter)
        self.le_2.setObjectName("le_2")
        self.verticalLayout_2.addWidget(self.le_2)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.le_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_3.setMinimumSize(QtCore.QSize(0, 25))
        self.le_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_3.setAlignment(QtCore.Qt.AlignCenter)
        self.le_3.setObjectName("le_3")
        self.verticalLayout_2.addWidget(self.le_3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.le_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_4.setMinimumSize(QtCore.QSize(0, 25))
        self.le_4.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_4.setAlignment(QtCore.Qt.AlignCenter)
        self.le_4.setObjectName("le_4")
        self.verticalLayout_2.addWidget(self.le_4)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.le_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_5.setMinimumSize(QtCore.QSize(0, 25))
        self.le_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.le_5.setAlignment(QtCore.Qt.AlignCenter)
        self.le_5.setObjectName("le_5")
        self.verticalLayout_2.addWidget(self.le_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbtn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_ok.setMinimumSize(QtCore.QSize(100, 0))
        self.pbtn_ok.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setWeight(50)
        font.setBold(False)
        self.pbtn_ok.setFont(font)
        self.pbtn_ok.setObjectName("pbtn_ok")
        self.horizontalLayout.addWidget(self.pbtn_ok)
        self.le_xc = QtWidgets.QLineEdit(self.centralwidget)
        self.le_xc.setMinimumSize(QtCore.QSize(0, 50))
        self.le_xc.setObjectName("le_xc")
        self.horizontalLayout.addWidget(self.le_xc)
        self.pbtn_save = QtWidgets.QPushButton(self.centralwidget)
        self.pbtn_save.setMinimumSize(QtCore.QSize(250, 0))
        self.pbtn_save.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pbtn_save.setFont(font)
        self.pbtn_save.setObjectName("pbtn_save")
        self.horizontalLayout.addWidget(self.pbtn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.le_ok = QtWidgets.QLineEdit(self.centralwidget)
        self.le_ok.setMinimumSize(QtCore.QSize(0, 125))
        self.le_ok.setObjectName("le_ok")
        self.verticalLayout.addWidget(self.le_ok)
        self.le_X = QtWidgets.QLineEdit(self.centralwidget)
        self.le_X.setMinimumSize(QtCore.QSize(0, 125))
        self.le_X.setObjectName("le_X")
        self.verticalLayout.addWidget(self.le_X)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        COS.setCentralWidget(self.centralwidget)

        self.retranslateUi(COS)
        QtCore.QMetaObject.connectSlotsByName(COS)

    def retranslateUi(self, COS):
        COS.setWindowTitle(QtWidgets.QApplication.translate("COS", "猜疑链生成器", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("COS", "猜疑链生成器", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("COS", "根据刘慈欣的《三体II:黑暗森林》制作 作者Minecraft理智游戏，QQ:1817515448", None, -1))
        self.le_num.setText(QtWidgets.QApplication.translate("COS", "请在这里输入要循环几次(要大于2)", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("COS", "模板", None, -1))
        self.pbtn_DF.setText(QtWidgets.QApplication.translate("COS", "黑暗森林猜疑链（在这里能制作,不点下方的,自己制作点下方的）", None, -1))
        self.pbtn_XD.setText(QtWidgets.QApplication.translate("COS", "星舰地球猜疑链（在这里能制作,不点下方的,自己制作点下方的）", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("COS", "自己制作", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("COS", "例:1.你不知道我是善意还是恶意;2.你不知道我认为你是善意还是恶意;3.你不知道我认为你认为我是善意还是恶意", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("COS", "你为第一内容，我为第二内容，不知道为第三内容，认为为第四内容,是善意还是恶意为第五内容", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("COS", "第一内容", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("COS", "第二内容", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("COS", "第三内容", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("COS", "第四内容", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("COS", "第五内容", None, -1))
        self.pbtn_ok.setText(QtWidgets.QApplication.translate("COS", "制作", None, -1))
        self.le_xc.setText(QtWidgets.QApplication.translate("COS", "请在这里输入你要第几项", None, -1))
        self.pbtn_save.setText(QtWidgets.QApplication.translate("COS", "保存制作结果", None, -1))
        self.le_ok.setText(QtWidgets.QApplication.translate("COS", "这里是制作结果", None, -1))
        self.le_X.setText(QtWidgets.QApplication.translate("COS", "这里是制作结果的第几项", None, -1))

